# Generated by Django 4.0.4 on 2022-06-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_tecnologias'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrabalhosFinaisDeCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(default=0)),
                ('titulo', models.CharField(max_length=100)),
                ('resumo', models.CharField(max_length=400)),
                ('imagem', models.ImageField(null=True, upload_to='media/')),
                ('relatorio', models.URLField(blank=True)),
                ('link_github', models.URLField(blank=True)),
                ('link_video', models.URLField(blank=True)),
                ('autores', models.ManyToManyField(related_name='autores', to='portfolio.pessoa')),
                ('orientadores', models.ManyToManyField(related_name='orientadores', to='portfolio.pessoa')),
            ],
        ),
    ]
