# Generated by Django 4.0.4 on 2022-06-05 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_trabalhosfinaisdecurso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabalhosfinaisdecurso',
            name='link_video',
        ),
    ]
